DELETE FROM body_parts;
INSERT INTO body_parts (id, type, gender, title)
VALUES (1,  'front', 'other', 'Head'),
       (2,  'front', 'other', 'Neck'),
       (3,  'front', 'other', 'Diaphragm'),
       (4,  'front', 'other', 'Chest'),
       (5,  'front', 'other', 'Abdomen'),
       (6,  'front', 'other', 'Pelvis'),
       (7,  'front', 'male', 'Penis'),
       (8,  'front', 'female', 'Vagina'),
       (9,  'front', 'other', 'Right Hips'),
       (10, 'front', 'other', 'Right Thigh'),
       (11, 'front', 'other', 'Right Knee'),
       (12, 'front', 'other', 'Right Shin'),
       (13, 'front', 'other', 'Right Ankle'),
       (14, 'front', 'other', 'Right Foot'),
       (15, 'front', 'other', 'Right Great toe'),
       (16, 'front', 'other', 'Right Toes'),
       (17, 'front', 'other', 'Right Shoulder'),
       (18, 'front', 'other', 'Right Upper Arm'),
       (19, 'front', 'other', 'Right Elbow'),
       (20, 'front', 'other', 'Right Forearm'),
       (21, 'front', 'other', 'Right Wrist'),
       (22, 'front', 'other', 'Right Palm'),
       (23, 'front', 'other', 'Right Thumb'),
       (24, 'front', 'other', 'Index finger of right hand'),
       (25, 'front', 'other', 'Middle finger of right hand'),
       (26, 'front', 'other', 'Ring finger of right hand'),
       (27, 'front', 'other', 'Little finger of right hand'),
       (28, 'front', 'female', 'Right Breast'),
       (29, 'front', 'other', 'Left Hips'),
       (30, 'front', 'other', 'Left Thigh'),
       (31, 'front', 'other', 'Left Knee'),
       (32, 'front', 'other', 'Left Shin'),
       (33, 'front', 'other', 'Left Ankle'),
       (34, 'front', 'other', 'Left Foot'),
       (35, 'front', 'other', 'Left Great toe'),
       (36, 'front', 'other', 'Left Toes'),
       (37, 'front', 'other', 'Left Shoulder'),
       (38, 'front', 'other', 'Left Arm'),
       (39, 'front', 'other', 'Left Elbow'),
       (40, 'front', 'other', 'Left Forearm'),
       (41, 'front', 'other', 'Left Wrist'),
       (42, 'front', 'other', 'Left Palm'),
       (43, 'front', 'other', 'Left Thumb'),
       (44, 'front', 'other', 'Index finger of left hand'),
       (45, 'front', 'other', 'Middle finger of left hand'),
       (46, 'front', 'other', 'Ring finger of left hand'),
       (47, 'front', 'other', 'Little finger of left hand'),
       (48, 'front', 'female', 'Left Breast'),
       (49, 'back', 'other', 'Back'),
       (50, 'back', 'other', 'Left Shoulder blade'),
       (51, 'back', 'other', 'Left Lower back'),
       (52, 'back', 'other', 'Left Buttock'),
       (53, 'back', 'other', 'Left Calf'),
       (54, 'back', 'other', 'Left Heel of foot'),
       (55, 'back', 'other', 'Left Back of elbow'),
       (56, 'back', 'other', 'Left Hand'),
       (57, 'back', 'other', 'Left Sole of foot'),
       (58, 'back', 'other', 'Right Shoulder blade'),
       (59, 'back', 'other', 'Right Lower back'),
       (60, 'back', 'other', 'Right Buttock'),
       (61, 'back', 'other', 'Right Calf'),
       (62, 'back', 'other', 'Right Heel of foot'),
       (63, 'back', 'other', 'Right Back of elbow'),
       (64, 'back', 'other', 'Right Hand'),
       (65, 'back', 'other', 'Right Sole of foot'),
       (66, 'front', 'other', 'Right Ear'),
       (67, 'front', 'other', 'Left Ear'),
       (68, 'front', 'other', 'Forehead'),
       (69, 'front', 'other', 'Nose'),
       (70, 'front', 'other', 'Chin'),
       (71, 'front', 'other', 'Right Eye'),
       (72, 'front', 'other', 'Left Eye'),
       (73, 'front', 'other', 'Mouth'),
       (74, 'front', 'other', 'Right Cheek'),
       (75, 'front', 'other', 'Left Cheek')
