DELETE FROM body_parts;

INSERT INTO body_parts(id, type, gender, title)
VALUES (1,  'front', 'other', 'Head'),
(2,  'front', 'other', 'Neck'),
(3,  'front', 'other', 'Diaphragm'),
(4,  'front', 'other', 'Chest'),
(5,  'front', 'other', 'Abdomen'),
(6,  'front', 'other', 'Pelvis'),
(7,  'front', 'male', 'Penis'),
(8,  'front', 'female', 'Vagina'),
(9,  'front', 'other', 'Right Hips'),
(10, 'front', 'other', 'Right Thigh'),
(11, 'front', 'other', 'Right Knee'),
(12, 'front', 'other', 'Right Shin'),
(13, 'front', 'other', 'Right Ankle'),
(14, 'front', 'other', 'Right Foot'),
(15, 'front', 'other', 'Right Great toe'),
(16, 'front', 'other', 'Right Toes'),
(17, 'front', 'other', 'Right Shoulder'),
(18, 'front', 'other', 'Right Upper Arm'),
(19, 'front', 'other', 'Right Elbow'),
(20, 'front', 'other', 'Right Forearm'),
(21, 'front', 'other', 'Right Wrist'),
(22, 'front', 'other', 'Right Palm'),
(23, 'front', 'other', 'Right Thumb'),
(24, 'front', 'other', 'Right Fingers'),
(25, 'front', 'female', 'Right Breast'),
(26, 'front', 'other', 'Left Hips'),
(27, 'front', 'other', 'Left Thigh'),
(28, 'front', 'other', 'Left Knee'),
(29, 'front', 'other', 'Left Shin'),
(30, 'front', 'other', 'Left Ankle'),
(31, 'front', 'other', 'Left Foot'),
(32, 'front', 'other', 'Left Great toe'),
(33, 'front', 'other', 'Left Toes'),
(34, 'front', 'other', 'Left Shoulder'),
(35, 'front', 'other', 'Left Arm'),
(36, 'front', 'other', 'Left Elbow'),
(37, 'front', 'other', 'Left Forearm'),
(38, 'front', 'other', 'Left Wrist'),
(39, 'front', 'other', 'Left Palm'),
(40, 'front', 'other', 'Left Thumb'),
(41, 'front', 'other', 'Left Fingers'),
(42, 'front', 'female', 'Left Breast'),
(43, 'back', 'other', 'Back'),
(44, 'back', 'other', 'Left Shoulder blade'),
(45, 'back', 'other', 'Left Lower back'),
(46, 'back', 'other', 'Left Buttock'),
(47, 'back', 'other', 'Left Calf'),
(48, 'back', 'other', 'Left Heel of foot'),
(49, 'back', 'other', 'Left Back of elbow'),
(50, 'back', 'other', 'Left Hand'),
(51, 'back', 'other', 'Left Sole of foot'),
(52, 'back', 'other', 'Right Shoulder blade'),
(53, 'back', 'other', 'Right Lower back'),
(54, 'back', 'other', 'Right Buttock'),
(55, 'back', 'other', 'Right Calf'),
(56, 'back', 'other', 'Right Heel of foot'),
(57, 'back', 'other', 'Right Back of elbow'),
(58, 'back', 'other', 'Right Hand'),
(59, 'back', 'other', 'Right Sole of foot'),
(60, 'front', 'other', 'Right Ear'),
(61, 'front', 'other', 'Left Ear'),
(62, 'front', 'other', 'Forehead'),
(63, 'front', 'other', 'Nose'),
(64, 'front', 'other', 'Chin'),
(65, 'front', 'other', 'Right Eye'),
(66, 'front', 'other', 'Left Eye'),
(67, 'front', 'other', 'Mouth'),
(68, 'front', 'other', 'Right Cheek'),
(69, 'front', 'other', 'Left Cheek')
