 ALTER TABLE auto_booking_schedules
    DROP CONSTRAINT automatic_booking_user_id_fkey,
    DROP COLUMN user_id,
    ALTER COLUMN clinic_consultation_duration DROP NOT NULL,
    ALTER COLUMN clinic_consultation_duration DROP DEFAULT,
    ALTER COLUMN clinic_consultation_price DROP NOT NULL,
    ALTER COLUMN clinic_consultation_price DROP DEFAULT,
    ALTER COLUMN clinic_consultation_payment_mode DROP NOT NULL,
    ALTER COLUMN clinic_consultation_payment_mode DROP DEFAULT,
    ALTER COLUMN home_visit_duration DROP NOT NULL, 
    ALTER COLUMN home_visit_duration DROP DEFAULT,
    ALTER COLUMN home_visit_price DROP NOT NULL, 
    ALTER COLUMN home_visit_price DROP DEFAULT,
    ALTER COLUMN home_visit_payment_mode DROP NOT NULL,
    ALTER COLUMN home_visit_payment_mode DROP DEFAULT,
    ALTER COLUMN online_consultation_duration DROP NOT NULL,
    ALTER COLUMN online_consultation_duration DROP DEFAULT,
    ALTER COLUMN online_consultation_price DROP NOT NULL,
    ALTER COLUMN online_consultation_price DROP DEFAULT,
    ALTER COLUMN online_consultation_payment_mode DROP NOT NULL,
    ALTER COLUMN online_consultation_payment_mode DROP DEFAULT;
